// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticket.DAL;

#nullable disable

namespace Ticket.DAL.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20230416034105_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("DeveloperId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("Ticket.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Department1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Department2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Department3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Department4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Department5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Department6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Department7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Department8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Department9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Department10"
                        });
                });

            modelBuilder.Entity("Ticket.DAL.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Depression"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("Ticket.DAL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 5,
                            Description = "this my discription..",
                            Title = "Dana"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Isaac"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 9,
                            Description = "this my discription..",
                            Title = "Damon"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 8,
                            Description = "this my discription..",
                            Title = "Miriam"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Terence"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Description = "this my discription..",
                            Title = "Roosevelt"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 9,
                            Description = "this my discription..",
                            Title = "Eduardo"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            Description = "this my discription..",
                            Title = "Wilbert"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            Description = "this my discription..",
                            Title = "Tasha"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            Description = "this my discription..",
                            Title = "Max"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 2,
                            Description = "this my discription..",
                            Title = "Bridget"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 8,
                            Description = "this my discription..",
                            Title = "Juan"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 10,
                            Description = "this my discription..",
                            Title = "Krystal"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 10,
                            Description = "this my discription..",
                            Title = "Erma"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 6,
                            Description = "this my discription..",
                            Title = "Orlando"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 5,
                            Description = "this my discription..",
                            Title = "Marvin"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 4,
                            Description = "this my discription..",
                            Title = "Lamar"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Joe"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 8,
                            Description = "this my discription..",
                            Title = "Wendell"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 4,
                            Description = "this my discription..",
                            Title = "Sandra"
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 6,
                            Description = "this my discription..",
                            Title = "Stephanie"
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Ervin"
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 4,
                            Description = "this my discription..",
                            Title = "Beth"
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Gretchen"
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 2,
                            Description = "this my discription..",
                            Title = "Gwendolyn"
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 7,
                            Description = "this my discription..",
                            Title = "Jerry"
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 6,
                            Description = "this my discription..",
                            Title = "Mitchell"
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 8,
                            Description = "this my discription..",
                            Title = "Maggie"
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 3,
                            Description = "this my discription..",
                            Title = "Sandy"
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 2,
                            Description = "this my discription..",
                            Title = "Lloyd"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("Ticket.DAL.Developer", null)
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticket.DAL.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticket.DAL.Ticket", b =>
                {
                    b.HasOne("Ticket.DAL.Department", "Department")
                        .WithMany("Tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Ticket.DAL.Department", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
